export default {
  name: 'seoSettings',
  title: 'SEO Settings',
  type: 'document',
  groups: [
    {
      name: 'basic',
      title: 'Basic SEO',
      default: true,
    },
    {
      name: 'social',
      title: 'Social Media',
    },
    {
      name: 'advanced',
      title: 'Advanced',
    },
    {
      name: 'analytics',
      title: 'Analytics',
    },
  ],
  fields: [
    {
      name: 'pageSlug',
      title: 'Page Slug',
      type: 'string',
      description: 'The slug of the page these SEO settings apply to',
      validation: (Rule: any) => Rule.required(),
      group: 'basic',
    },
    {
      name: 'pageName',
      title: 'Page Name',
      type: 'string',
      description: 'Internal name for this page',
      validation: (Rule: any) => Rule.required(),
      group: 'basic',
    },
    {
      name: 'title',
      title: 'SEO Title',
      type: 'string',
      description: 'Title tag for the page (50-60 characters)',
      validation: (Rule: any) => Rule.required().max(60).warning('Should be between 50-60 characters'),
      group: 'basic',
    },
    {
      name: 'titlePreview',
      title: 'Title Preview',
      type: 'string',
      description: 'This is how your title will appear in search results',
      readOnly: true,
      hidden: ({document}: any) => !document?.title,
      group: 'basic',
    },
    {
      name: 'description',
      title: 'Meta Description',
      type: 'text',
      rows: 3,
      description: 'Description for search engines (150-160 characters)',
      validation: (Rule: any) => Rule.required().max(160).warning('Should be between 150-160 characters'),
      group: 'basic',
    },
    {
      name: 'keywords',
      title: 'Keywords',
      type: 'array',
      of: [{type: 'string'}],
      description: 'Keywords for search engines (5-10 recommended)',
      validation: (Rule: any) => Rule.max(10),
      group: 'basic',
    },
    {
      name: 'focusKeyword',
      title: 'Focus Keyword',
      type: 'string',
      description: 'Primary keyword to optimize this page for',
      group: 'basic',
    },
    {
      name: 'canonicalUrl',
      title: 'Canonical URL',
      type: 'url',
      description: 'The canonical URL for this page (optional, defaults to page URL)',
      group: 'advanced',
    },
    {
      name: 'priority',
      title: 'Sitemap Priority',
      type: 'number',
      description: 'Priority for sitemap (0.0 to 1.0)',
      validation: (Rule: any) => Rule.min(0).max(1),
      initialValue: 0.5,
      group: 'advanced',
    },
    {
      name: 'changeFrequency',
      title: 'Change Frequency',
      type: 'string',
      description: 'How often this page changes',
      options: {
        list: [
          {title: 'Always', value: 'always'},
          {title: 'Hourly', value: 'hourly'},
          {title: 'Daily', value: 'daily'},
          {title: 'Weekly', value: 'weekly'},
          {title: 'Monthly', value: 'monthly'},
          {title: 'Yearly', value: 'yearly'},
          {title: 'Never', value: 'never'},
        ],
      },
      initialValue: 'monthly',
      group: 'advanced',
    },
    {
      name: 'noIndex',
      title: 'No Index',
      type: 'boolean',
      description: 'If checked, search engines will not index this page',
      initialValue: false,
      group: 'advanced',
    },
    {
      name: 'noFollow',
      title: 'No Follow',
      type: 'boolean',
      description: 'If checked, search engines will not follow links on this page',
      initialValue: false,
      group: 'advanced',
    },
    {
      name: 'ogTitle',
      title: 'Open Graph Title',
      type: 'string',
      description: 'Title for social media sharing (optional, defaults to SEO title)',
      group: 'social',
    },
    {
      name: 'ogDescription',
      title: 'Open Graph Description',
      type: 'text',
      rows: 3,
      description: 'Description for social media sharing (optional, defaults to meta description)',
      group: 'social',
    },
    {
      name: 'ogType',
      title: 'Open Graph Type',
      type: 'string',
      description: 'The type of content',
      options: {
        list: [
          {title: 'Website', value: 'website'},
          {title: 'Article', value: 'article'},
          {title: 'Profile', value: 'profile'},
          {title: 'Business', value: 'business.business'},
        ],
      },
      initialValue: 'website',
      group: 'social',
    },
    {
      name: 'ogImage',
      title: 'Open Graph Image',
      type: 'image',
      description: 'Image for social media sharing (1200x630px recommended)',
      options: {
        hotspot: true,
      },
      fields: [
        {
          name: 'alt',
          type: 'string',
          title: 'Alternative text',
        },
      ],
      group: 'social',
    },
    {
      name: 'twitterCard',
      title: 'Twitter Card Type',
      type: 'string',
      description: 'Type of Twitter card',
      options: {
        list: [
          {title: 'Summary', value: 'summary'},
          {title: 'Summary Large Image', value: 'summary_large_image'},
        ],
      },
      initialValue: 'summary_large_image',
      group: 'social',
    },
    {
      name: 'twitterTitle',
      title: 'Twitter Title',
      type: 'string',
      description: 'Title for Twitter sharing (optional, defaults to Open Graph title)',
      group: 'social',
    },
    {
      name: 'twitterDescription',
      title: 'Twitter Description',
      type: 'text',
      rows: 3,
      description: 'Description for Twitter sharing (optional, defaults to Open Graph description)',
      group: 'social',
    },
    {
      name: 'twitterImage',
      title: 'Twitter Image',
      type: 'image',
      description: 'Image for Twitter sharing (optional, defaults to Open Graph image)',
      options: {
        hotspot: true,
      },
      fields: [
        {
          name: 'alt',
          type: 'string',
          title: 'Alternative text',
        },
      ],
      group: 'social',
    },
    {
      name: 'structuredData',
      title: 'Structured Data',
      type: 'text',
      description: 'JSON-LD structured data for this page (JSON format)',
      rows: 10,
      group: 'advanced',
    },
    {
      name: 'redirects',
      title: 'Redirects',
      type: 'array',
      of: [
        {
          type: 'object',
          fields: [
            {
              name: 'from',
              title: 'From URL',
              type: 'string',
              validation: (Rule: any) => Rule.required(),
            },
            {
              name: 'type',
              title: 'Redirect Type',
              type: 'string',
              options: {
                list: [
                  {title: '301 (Permanent)', value: '301'},
                  {title: '302 (Temporary)', value: '302'},
                ],
              },
              initialValue: '301',
            },
          ],
        },
      ],
      group: 'advanced',
    },
    {
      name: 'lastModified',
      title: 'Last Modified',
      type: 'datetime',
      description: 'When this page was last modified',
      readOnly: true,
      group: 'analytics',
    },
    {
      name: 'seoScore',
      title: 'SEO Score',
      type: 'number',
      description: 'Calculated SEO score (0-100)',
      readOnly: true,
      group: 'analytics',
    },
  ],
  preview: {
    select: {
      title: 'pageName',
      subtitle: 'title',
      media: 'ogImage',
    },
    prepare({title, subtitle, media}: {title: string; subtitle: string; media: any}) {
      return {
        title: title || 'Untitled Page',
        subtitle: subtitle || 'No SEO title set',
        media,
      }
    },
  },
}
